### ISSUE TITLE
not connecting to the UI

### ISSUE THREAD

**Issue by fabiofusco-rre** [davidramosweb/hassio-addons#3]
Hi,
now I am not able to connect to my UI.

How can I delete/fix the add-on?

Thanks

**Comment by MahrWe** [comment]
Hi Fabio,

given your clients are connected to the WiFi by hostapd and have an IP-address assigned which should match the subnet 192.168.99.0. You can access your home-assistant (running on the same device as hostapd) at the address 192.168.99.1

Best,
MahrWe
